language: node_js
node_js:
  - "10"
  - "12"

cache:
  directories:
    - "node_modules"

install:
  - yarn install

script:
  # Test Statusfy
  - yarn run lint

  - yarn run test:demo && yarn run test
